name = "ConditionalDeepSDFs"
uuid = "fe778f04-226f-461d-823c-279f32d444e5"
version = "0.1.0"
authors = ["Azamat Berdyshev <aberdysh@gmail.com>"]

[deps]
AliasTables = "66dad0bd-aa9a-41b7-9441-69ab47430ed8"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AliasTables = "1.1.3"
CUDA = "5.9.6"
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.12.0"
Lux = "1.31.3"
LuxCore = "1.5.3"
Meshing = "0.7.0"
NNlib = "0.9.33"
Polyester = "0.7.19"
Random = "1.11.0"
Statistics = "1.11.1"
